# Markdownlint configuration for ai-companion

# MD013: Line length
MD013:
  line_length: 100
  code_blocks: false
  tables: false

# MD033: Allow inline HTML (for GitHub-specific features)
MD033: false

# MD041: First line in file should be a top level header
MD041: false

# MD046: Code block style (allow both fenced and indented)
MD046:
  style: "fenced"

# MD024: Multiple headers with the same content
MD024:
  allow_different_nesting: true

# MD034: Bare URL used (allow for install commands)
MD034: false