# StyLua configuration for ai-companion

# Basic formatting options
indent_type = "Spaces"
indent_width = 2
column_width = 100
line_endings = "Unix"

# Quote style
quote_style = "AutoPreferDouble"

# Function call parentheses
call_parentheses = "Always"

# Collapse simple statements
collapse_simple_statement = "Never"